### ISSUE TITLE
if you forget to upload a script like vcf2ShatterSeek.delly.py

### ISSUE THREAD

**Issue by SeqCrafter** [pengweixing/ecDNA-on-GCA#1]
your vcf2ShatterSeek.novobreak.py can only be used for the output from novobreak, can not for delly. and your another script <<merge.novobreak.delly.py>> need delly file format most like novobreak? So if you forget to upload a script like vcf2ShatterSeek.delly.py ?

**Comment by pengweixing** [comment]
I just uploaded the script(delly.vcf2ShatterSeek.py) for delly.

The usage is shown as follow:

python delly.vcf2ShatterSeek.py delly.pass.vcf delly.pass.matrix
python vcf2ShatterSeek.novobreak.py novoBreak.pass.flt.vcf novoBreak.pass.flt.matrix
python merge.novobreak.delly.py novoBreak.pass.flt.matrix delly.pass.matrix > delly.novobreak.matrix

**Comment by SeqCrafter** [comment]
> I just uploaded the script(delly.vcf2ShatterSeek.py) for delly.
> 
> The usage is shown as follow:
> 
> python delly.vcf2ShatterSeek.py delly.pass.vcf delly.pass.matrix python vcf2ShatterSeek.novobreak.py novoBreak.pass.flt.vcf novoBreak.pass.flt.matrix python merge.novobreak.delly.py novoBreak.pass.flt.matrix delly.pass.matrix > delly.novobreak.matrix

Thank you so much for your efficient reply!
